### ISSUE TITLE
What is the helios license?

### ISSUE THREAD

**Issue by mkdolan** [benadida/helios-server#102]
Hi, what is the open source license being used for helios-server? Where can I find the license information?

Thanks,

Mike Dolan
The Linux Foundation

**Comment by benadida** [comment]
Hi Mike,

We recently discussed this on the Helios mailing list, and agreed on Apache 2. I'll add a LICENSE file to clarify.

**Comment by benadida** [comment]
done!

**Comment by mkdolan** [comment]
Thanks!
