### ISSUE TITLE
Bulk upload of voters doesn't work

### ISSUE THREAD

**Issue by emerout** [benadida/helios-server#109]
Hello,

I have just installed Helios from master on an Debian server. 
I may create an election but I can't upload a CSV voters file.
I have the preview of the file but choosing let's go doesn't do anything and the file is still not yet processed.

Here is my configuration file : [settings.txt](https://github.com/benadida/helios-server/files/41081/settings.txt)

Thanks for your help
Regards
Claire

**Comment by benadida** [comment]
are you running the background process?

`python manage.py celeryd`

**Comment by emerout** [comment]
Got it !
celeryd was not started.
It is documented in doc on http://documentation.heliosvoting.org/install but not in repo Install.md file.

Thanks a lot,
Claire.

**Comment by changuinho2000** [comment]
I am trying to run a helios vote in a browser...when I try to upload the bulk voter file, I get this error 
"There was an error while handling your request. "
