### ISSUE TITLE
Implement voting_starts_at/ends_at/extended_until

### ISSUE THREAD

**Issue by RunasSudo** [benadida/helios-server#134]
The logic seems to be there, along with half of the interface. Is there any reason this hasn't been fully implemented yet?

I've completed the implementation of these fields on my fork at https://github.com/RunasSudo/helios-server-mixnet/commit/4a9ae3d7360ed50f066a9cb68703774056a7f526 and https://github.com/RunasSudo/helios-server-mixnet/commit/7edba64e8f6c1db4bd3013826a0d179bf0487fed.

**Comment by benadida** [comment]
No good reason other than time, if I remember correctly :)

Would love a pul request!

**Comment by RunasSudo** [comment]
@benadida Cool, I've opened a PR at #136.
