### ISSUE TITLE
Can't add trustees

### ISSUE THREAD

**Issue by vvv214** [benadida/helios-server#139]
When I try to add trustees from vote.helios-voting.org, the trustee can receive the link, but will report an error following that link.

**Comment by benadida** [comment]
is this happening to you right now on heliosvoting.org?

**Comment by vvv214** [comment]
Yes. Does the trustee need to perform some work beforehand?

**Comment by vvv214** [comment]
I'm pasting the link of the test election here:
https://vote.heliosvoting.org/helios/elections/65ad951a-acf8-11e6-a0a9-f6a462717fb7/trustees/view

**Comment by benadida** [comment]
just tested adding myself as a trustee to that election and it works fine. Can you tell me which trustee you're trying to log in as?

**Comment by vvv214** [comment]
Hi Ben,

Now I can successfully walk through the whole process. Thank you! 

I saw your test. I just add the email address for myself. Previously, I can receive the email from helios-voting, but once I open the link, it gives me an error. As you can see, I added several trustees. So all the computations of trustees are done by js on trustees' browsers, and all central server's computations are done in the back-end?

**Comment by benadida** [comment]
I missed the followup here, I'm sorry!

All private-key computations by trustees are done inside your browser, the private key never goes to the server.
