### ISSUE TITLE
Non-ASCII names are displayed in question marks

### ISSUE THREAD

**Issue by ChALkeR** [benadida/helios-server#141]
Not sure if this is the correct place to report this issue, sorry, if not.

vote.linuxfoundation.org screenshot:
![screenshot_20160121_231509](https://cloud.githubusercontent.com/assets/291301/12493252/43b90908-c095-11e5-91ed-bbc75f31146a.png)

identity.linuxfoundation.org screenshot:
![screenshot_20160121_232610](https://cloud.githubusercontent.com/assets/291301/12493514/61d3a4f6-c096-11e5-99a2-5c15f2ac3a55.png)

Those screenshots are from last year, but it's the same this year =). I'm using login via GitHub.

It doesn't bother me much, but the name on `/voters/list` page is also displayed in question marks, which could (and did) raise concerns =).

**Comment by benadida** [comment]
this is the right place indeed! Is this happening on vote.heliosvoting.org, or on a different install of Helios?

**Comment by benadida** [comment]
oh it looks like a diff install given the login logo. Got it. There might be some custom code here that is not part of the Helios codebase.
