### ISSUE TITLE
clear and up2date installation instructions wanted

### ISSUE THREAD

**Issue by mhow2** [benadida/helios-server#142]
Hi,

Well, I tried to install Helios on ubuntu 14.04, following https://github.com/benadida/helios-server/blob/master/INSTALL.md. It doesn't work.
I tried to mix-up with http://documentation.heliosvoting.org/install but it's overwhelming. Especially at the step when it comes to settings.py which doesn't contains any settings for database username/password.

The software needs clear installation instructions and maybe a ready-to-use docker build. It fits well with docker as so many times, voting is an instant / narrow time-frame to handle. Start it, vote it then close it when finished.

**Comment by benadida** [comment]
can you say more about how things fail following `INSTALL.md` instructions?

**Comment by benadida** [comment]
seeing no further comments, closing this one. I think `INSTALL.md` works well, but please reopen if it doesn't!
