### ISSUE TITLE
problem while altering the fields of the proof

### ISSUE THREAD

**Issue by thomas-souliotis** [benadida/helios-server#143]
My thesis is about implementing preferential/range voting in homomorphic systems, and I chose helios for my practical implementation. As my proof is different, let's say that my main problem is how to add some additional Fields in the overall_proof, rather than just having A and B.
I have done the proper changes in elgamal.js to produce the correct results, and I have also added the new fields needed in legacy.py, elgamal.py, algs.py, but nothing works. Even the auditing of a specific  vote shows the regular A,B in the commitment part and doesn't show the new added fields. Even if I just rename A or B, problems still remain(the fields are not shown in the audit part, and the vote is not casted if i have changed the python files).
So is there any solution to the above?

**Comment by benadida** [comment]
Hi there. It's hard to solve this problem without seeing your code. I suggest posting this as a ticket on your code changes? Closing this issue for now as it doesn't refer to the Helios codebase itself.
