### ISSUE TITLE
Limit to 20 answers

### ISSUE THREAD

**Issue by Ayertienna** [benadida/helios-server#145]
It feels like a silly question, but is there any reason that the limit of possible answers to choose is 20? We have a use case where this is not enough.

**Comment by benadida** [comment]
where are you seeing this limitation? on vote.heliosvoting.org? Somewhere else?

**Comment by Ayertienna** [comment]
Yes, when adding a question.
<img width="1466" alt="helios_limit" src="https://cloud.githubusercontent.com/assets/529760/23351282/8200986c-fcc0-11e6-8a37-0e55387a215d.png">

**Comment by benadida** [comment]
Ah I see, I thought you meant the total number of answers you can offer was limited to 20.. and it's not of course. But you're actually looking to, say, have a question with 40 possible answers and give voters the option of voting for up to 20 but no more? That is fairly unusual :)

The reason there's a limit is that the computational cost of the proof for such a vote is pretty high. If it's really what you want to do, I can look into softening it, but it may take a while to encrypt your user's ballot in their browser.

**Comment by Ayertienna** [comment]
Yes, we're looking into ways of doing general elections for a council of an organisation in which there are about 40+ seats to distribute and (for now) everyone can assign all the seats to candidates.. This system might change (we do see the problems it causes), but for now, these are the rules we've set for ourselves ;-)

If it is only a matter of time for computing the encryption, then softening this limit would be greatly appreciated, thanks!

**Comment by benadida** [comment]
sorry for the delay on this... would it be an option for you to say "vote for as many as you like" and take the ones with the highest number of votes, however many you need? I'll up the limit in parallel, but I think your voters will have a nicer experience this way.

**Comment by benadida** [comment]
I've updated Helios and the main web site vote.heliosvoting.org to go up to 50. Pretty crummy UI for now, but it should do the trick for you.

**Comment by Ayertienna** [comment]
Thank you! (and sorry for the late comment)
From the UI perspective, wouldn't it make more sense to just leave this as a text field? (I'm asking partially since there might sometimes be more than 50 options..)

**Comment by benadida** [comment]
yeah, the UI could use some help, but for the purposes of this ticket, I think I will close this and rethink the UI more holistically at some point.
