### ISSUE TITLE
Voters accessing "Voters and Ballot Tracking Center"

### ISSUE THREAD

**Issue by massonpj** [benadida/helios-server#147]
Eligible voters in an election, after logging in, can access a page that lists the alias, Smart Ballot Tracker hash, number of votes cases, and which aliases have voted/not voted. Is this by design? If so can you please explain the rationale behind this.

Image/screenshot attached.
![screenshot from 2017-03-07 12-54-03](https://cloud.githubusercontent.com/assets/5924352/23865929/a677eadc-07ed-11e7-9a70-d85b1eefdfec.png)

**Comment by benadida** [comment]
Hi @massonpj , yes that is definitely by design. The idea of verifiable elections like Helios is that anyone can watch the voting process happen as an extra auditing step. This helps ensure that votes don't mysteriously disappear, for example. Is this causing you pain?

**Comment by massonpj** [comment]
Thanks @ benadida, that makes sense. No pain at all--in fact, Helios has made much of the pain we had during elections disappear (but not mysteriously)
