### ISSUE TITLE
Weighted Voting

### ISSUE THREAD

**Issue by FarazFe** [benadida/helios-server#176]
Hello there,
I want to pick up your brain about implementing weighted voting.
Is it okay to loop over tally.add_vote() to achieve this for integer weights?

**Comment by benadida** [comment]
Weighting by voter type? Yes, you could do it this way indeed as long as the weights are public.

**Comment by deshario** [comment]
@FarazFe Is it something like vote * weight of each person ? Can you share your code plz

**Comment by biscofil** [comment]
@benadida 

Good morning! I am working on my Master's degree on voting systems and digging into Helios I'm having difficulties understanding the actual implementation. In "Electing a University President using Open-Audit Voting: Analysis of real-world use of Helios" you mention vote weights as one of the main reasons for MixNets being dropped but I can't find any reference to weights in the current repository, am I missing something?

Are you currently using weight, were those only proposed or eventually dropped?

Many thanks!
