### ISSUE TITLE
Link to vote

### ISSUE THREAD

**Issue by foguinhoperuca** [benadida/helios-server#179]
Hello!

I 've deployed the helios system and everything is OK except by the following problem:

The link (button) to vote is broken in election's page (http://e-vote.sorocaba.sp.gov.br/helios/elections/<election_uuid_goes_here>/view). It is missing helios/ part in link:

http://e-vote.sorocaba.sp.gov.br/booth/vote.html?election_url=%2Fhelios%2Felections%2F<election_uuid_goes_here> (broken)

http://e-vote.sorocaba.sp.gov.br/helios/booth/vote.html?election_url=%2Fhelios%2Felections%2F<election_uuid_goes_here> (working) - Note the "extra" helios/ path.

This very same error is ocurring with the link in e-mail sended to elector:
http://e-vote.sorocaba.sp.gov.br/helios/e/best-gnu-linux/vote **convert to** http://e-vote.sorocaba.sp.gov.br/booth/vote.html?election_url=%2Fhelios%2Felections%2F<election_uuid_goes_here> **but it should be converted to** http://e-vote.sorocaba.sp.gov.br/helios/booth/vote.html?election_url=%2Fhelios%2Felections%2F<election_uuid_goes_here>

So, I added the following simple hack to fix it (it fixed the first link's error):

**helios/views.py:306**
```python
# FIXME added manually helios/ in url. Verify if nothing will break...
#  vote_url = "%s/booth/vote.html?%s" % (settings.SECURE_URL_HOST, urllib.urlencode({'election_url' : reverse(one_election, args=[election.uuid])}))
  vote_url = "%s/helios/booth/vote.html?%s" % (settings.SECURE_URL_HOST, urllib.urlencode({'election_url' : reverse(one_election, args=[election.uuid])}))
```

But I am guessing that I missed some simple configuration, otherwise, this simple bug would be reported early (and fixed).

I was looking into source code and found the variable called **SECURE_URL_HOST** but this very same variable is setting in settings.py, so I don't know if this variable has anything to do with the problem. Anyway, I setted it as the follow:

**settings.py:194**
```python
# The two hosts are here so the main site can be over plain HTTP
# while the voting URLs are served over SSL.
URL_HOST = get_from_env("URL_HOST", "http://e-vote.sorocaba.sp.gov.br").rstrip("/")

# IMPORTANT: you should not change this setting once you've created
# elections, as your elections' cast_url will then be incorrect.
# SECURE_URL_HOST = "https://localhost:8443"
SECURE_URL_HOST = get_from_env("SECURE_URL_HOST", URL_HOST).rstrip("/")
```
Note that I don't added anything after the final ".br" ("/" neither port number or even /helios).

So, this configurations is correct? There is any other way to fix the problem with the link? How to fix the second link?

Thanks for your help,
Jefferson Campos

**Comment by shirlei** [comment]
@foguinhoperuca so you solved you issue  .cache OSError (https://github.com/benadida/helios-server/issues/178)? If so, please post your follow up so others can learn later! 
What you are experiencing now seems like some problem with you web server deployment, nothing related to the mentioned settings. Are you using Apache? Django serves urls as declared at every apps' urls.py, so it should be adding /helios/ to your urls when necessary. So my guess is that you should focus on checking how the apps/urls flow are working in your deployment.

**Comment by benadida** [comment]
closing this, as I think @shirlei has the right advice.
