### ISSUE TITLE
Different jTemplate versions

### ISSUE THREAD

**Issue by shirlei** [benadida/helios-server#183]
Hi! I would like to know if is there any reason to have different versions of jTemplate?
I understand that (1) was updated in commit 4e33d808 in order to use tag {#for}, but couldn't (2) and (3) be updated as well?

1) helios/media/helios/jquery-jtemplates.js:/* jTemplates 0.8.4 (http://jtemplates.tpython.com) Copyright (c) 2007-2013 Tomasz Gloc */

2) heliosbooth/js/jquery-jtemplates.js:/* jTemplates 0.6.6 (http://jtemplates.tpython.com) Copyright (c) 2008 Tomasz Gloc (http://www.tpython.com)

3) heliosverifier/js/jquery-jtemplates.js:/* jTemplates 0.6.6 (http://jtemplates.tpython.com) Copyright (c) 2008 Tomasz Gloc (http://www.tpython.com)

thank you!

**Comment by benadida** [comment]
no good reason, I believe, feel free to submit a PR to update all to the latest!
