### ISSUE TITLE
Guide for independent booth?

### ISSUE THREAD

**Issue by karel-3d** [benadida/helios-server#185]
I am trying to get independent voting booth working.

But I am not sure where to start. Do you have some quick rundown what is needed? I am not sure where to put `election_url` and how is login handled

**Comment by karel-3d** [comment]
...oh I see, `election_url` is from query :D nice

**Comment by karel-3d** [comment]
...and well, helios own URLs don't work for me, since the server has no CORS headers. :( I will make another issue for that

**Comment by benadida** [comment]
We don't have this fully working at this point, it was kind of a dream feature a few years back. I'll close the issue and we can discuss CORS on the other issue you opened.
