### ISSUE TITLE
Helios website documentation is NOT WORKING

### ISSUE THREAD

**Issue by stanleycelestin1** [benadida/helios-server#210]
Technical Documentation Link on https://heliosvoting.org/docs  is **NOT WORKING** :(

**Comment by shirlei** [comment]
Hi! Please see https://groups.google.com/forum/#!topic/helios-voting/vp_pX8X_hTs

**Comment by stanleycelestin1** [comment]
@shirlei Thank you that help:

solution: open docs link in incognito moded
