### ISSUE TITLE
Developers/sysadmin of heliosvoting.org

### ISSUE THREAD

**Issue by Spacial** [benadida/helios-server#226]
Hi,

there is any mailling list and/or contact with sysadmins of the site?

We have some questions, but there isnt any wiki/extensive documentation and help@heliosvoting doesn't answered us.

Thank you.

**Comment by shirlei** [comment]
Hi there, did you take a look at https://groups.google.com/forum/#!forum/helios-voting ?

**Comment by Spacial** [comment]
didn't foudd it, thank you Shirlei!

**Comment by Spacial** [comment]
sorry to bother again. Is there any election configuration on Helios to support a subgroup of trustees? like needed 3 of 5 to decrypt and tally votes? :)
