### ISSUE TITLE
Inaccurate message for Approval Voting

### ISSUE THREAD

**Issue by DavidMertz** [benadida/helios-server#247]
I just voted in the PSF Board election using Helios.  In that election, 26 candidates are running, and we utilize Approval Voting (because of me, it happens; I was previously Election Administrator and contributor to the other software used before PSF adopted Helios).

After selecting my slate of candidates (11 in my case, for 4 seats), I was presented with this message:

>     [you under-voted: you may select up to 26]

This is a bit inaccurate.  A vote for 11 candidates (or indeed for any number 0 through 26) is not an **undervote** with Approval Voting.  That screen presents users with an opportunity to edit their votes, which is good and reasonable; the message is simply likely to be misleading.

A better phrase might be, e.g.:

> [you selected $N$ candidate; you may select from zero to $M$]

In any case, something that does not insinuate a ballot is invalid as completed.

**Comment by nealmcb** [comment]
Thank you, David.  My sense is that a vote for some choices, but less than the maximum number of choices, is not "an undervote".

In fact, my colleagues and I submitted feedback to the Election Assistance Commission to that effect:
  Comment from Celeste Landry and LWV of Boulder County (CO) Voting Methods Team
   https://www.regulations.gov/document?D=EAC-2020-0002-0061
   See 1.1.10-P – Report undervotes for each contest 

But I have two questions.

1)  Did this change apply to all contests, both Approval voting and plurality voting?

2)  It is normally useful to get a count of how many voters cast a "blank contest". We'd also love to track "blank ballots",where all the contests on the ballot are blank. That helps assess the "residual vote" which provides information on voter interest, how informed voters are, how well the ballot is designed, etc. and is one of the most fundamental election quality indications we have.
So I would call a vote with no approvals an "undervote", and would want a count of them.
But I wonder if that is possible in Helios.  Is there any way to track at least that statistic?

**Comment by DavidMertz** [comment]
I believe the change at https://github.com/benadida/helios-server/pull/248/files will do what you wish. Helios assigns a min and Max for vote number.  But you probably need Ben, or another real developer if the software to opine more conclusively.

Shout out to Boulder where I grew up.
