### ISSUE TITLE
Voters with Yahoo/Outlook mail account don't receive e-mail with credentials

### ISSUE THREAD

**Issue by tudorgrig** [benadida/helios-server#252]
Hi, I've created an election and my Outlook voters don't receive the email. They checked Spam/Delete folders and waited for hours. Yahoo voters are also experiencing this, they don't receive the e-mails

**Comment by mjeromin** [comment]
Is this issue for your own Helios server or an election created on [heliosvoting.org](https://heliosvoting.org)? If the latter, have you sent an email to the administrators? help@heliosvoting.org

If you're seeing emails successfully received at other mailbox providers (ie. Gmail) but not Outlook or Yahoo, then this is probably not a software issue with helios-server. More likely, it is a mail deliverability issue. Yahoo describes a number of factors which could impact deliverability in their [FAQs](https://help.yahoo.com/kb/postmaster/yahoo-mail-deliverability-faqs-sln24439.html). Outlook.com hosts a similar [postmaster page](https://sendersupport.olc.protection.outlook.com/pm/).
