### ISSUE TITLE
Freezing election no longer opens voting

### ISSUE THREAD

**Issue by tomwthomas** [benadida/helios-server#263]
In one of the last couple of commits (August changes) there was a bug introduced that prevents the polls from being forced open.  

Previously when you clicked on "freeze ballot and open election." in the admin tool it did just that.  Now when you click the link it changes the next step to be visually correct, but it says voting is not yet open, and prevents ballots from being cast.

See screenshots for unexpected behavior.

![pre freeze](https://user-images.githubusercontent.com/1120015/91917310-64d0fa00-ec74-11ea-90d8-a0d5edfa6f4b.PNG)
![post freeze](https://user-images.githubusercontent.com/1120015/91917311-65699080-ec74-11ea-8b32-dc4b636fca84.PNG)

**Comment by benadida** [comment]
@tomwthomas are you sure it's not a problem with the opening time of your election, since it says that the election opening time is 9/2 2pm?

**Comment by tomwthomas** [comment]
Issue with our instance not saving the polling times enabling unexpected behavior masked by what the GUI is showing e.g. it does not show the polls will open at a future date/time.
