### ISSUE TITLE
Celery not starting

### ISSUE THREAD

**Issue by wbigger** [benadida/helios-server#271]
With the last update of middle 2020, celery was updated to 4.

This means that the `python manage.py celeryd` doesn't work anymore.

After some attempts, I fixed the issue calling directly the following command:

```sh
celery worker --app helios --events --beat --concurrency 1 --logfile celeryw.log --pidfile celeryw.pid
```

It seems to work, but I am not sure it is the right solution.

It is OK? Or is there some problem with it?

**Comment by benadida** [comment]
That was it! This is now fixed.
