### ISSUE TITLE
Using the credentials from the election email  leads to Bad ID or password

### ISSUE THREAD

**Issue by bmalbusca** [benadida/helios-server#278]
I have the problem that the login credential sent to the voters is giving a bad ID or password error. Did someone have the same issue?

**Comment by changuinho2000** [comment]
I know what could be happening...ppl receive a login and password.... But ppl try to vote from the cell phone, where the login is actually Login, so its L in capital and not l (lower case). Another thing that people complained is that typing the password should take them to an error, but I think its the Capital login user problem.... I hope ben can help me with this error "There was an error while handling your request." when adding txt, csv bulk upload voters files

**Comment by benadida** [comment]
this is an issue with mistyping.
