### ISSUE TITLE
Error when uploading voters

### ISSUE THREAD

**Issue by chatuba2** [benadida/helios-server#279]
Hi, 

I'm trying to bulk upload the CSV file to the Helios website, but after uploading I'm getting this error: "There was an error while handling your request".

I tried to upload a comma separated TXT file and it goes to the table preview window and the table looked as it should. After confirming I got the same error message. The same happened when I tried to login with my google account to vote in a public election.

I tried everything but I coudn't find a way to upload the voters list. 
Is this a known problem? Is there any solutions? Can anyone help me?

Thanks so much!

**Comment by jeremylow** [comment]
Having this same issue even using a previous voting list.

**Comment by benadida** [comment]
Looks like we went over quota for the AMQP queue, and had to up our quota. Sorry about this, there was no alert on this new service. Fixed now.

**Comment by jeremylow** [comment]
Awesome. You're the best!
