### ISSUE TITLE
Automate audit of votes

### ISSUE THREAD

**Issue by bartdjow** [benadida/helios-server#297]
Is it possible to force or automate the ballot audit, before depositing it in the ballot box?

**Comment by BenSmyth** [comment]
Forced/automated auditing before casting is incompatible with the design decision not to audit cast ballots.

Auditing reveals data that can be used for ballot reconstruction, allowing voters to prove how they voted, permitting vote selling.

**Comment by benadida** [comment]
@BenSmyth is right. It's a little bit confusing, but it's audit *or* cast, not both.
