### ISSUE TITLE
Github authentication method

### ISSUE THREAD

**Issue by lizthegrey** [benadida/helios-server#315]
As part of running the @open-telemetry elections, we'd like users to be able to directly log in with github rather than google credentials so we don't have to track down peoples' emails. Is a github auth provider a contribution you'd accept, @benadida?

**Comment by benadida** [comment]
very much so yes! Thank you for checking @lizthegrey.

**Comment by lizthegrey** [comment]
can this be enabled on heliosvoting.org so I can close out this issue @benadida?

**Comment by benadida** [comment]
@lizthegrey sorry for the delay, just deployed and enabled this on prod. Let me know if you hit any snags! And thanks again for the contribution.

**Comment by lizthegrey** [comment]
Great. I'll open a PR to be able to bulk upload a list of GH voters, and then we'll run the @open-telemetry election!

**Comment by benadida** [comment]
Fantastic!

**Comment by lizthegrey** [comment]
this approach seem fine to you @benadida? https://github.com/benadida/helios-server/pull/320

**Comment by lizthegrey** [comment]
Bulk upload is merged, will close issue once available on http://heliosvoting.org/

**Comment by lizthegrey** [comment]
Verified working on vote.helios
