### ISSUE TITLE
The Voters & Ballot menu is error

### ISSUE THREAD

**Issue by Kammilaa** [benadida/helios-server#321]
when I tried to open the voters & ballot menu there is some error. The notif said that "an error occurred in the application and your page could not be served". the notif also said that the application owner needs to check the logs for details. What must I do?
![WhatsApp Image 2021-10-06 at 05 23 32](https://user-images.githubusercontent.com/92028140/136192306-b2ebbcfa-e200-425e-a7dc-aa0af3d20b9c.jpeg)

**Comment by benadida** [comment]
Hi @Kammilaa, the Helios server is under unexpected load right now, the job queue is working through the backlog, things should be back within a few hours. I'm sorry for the trouble!
