### ISSUE TITLE
Votes aren't getting registered on self-hosted server

### ISSUE THREAD

**Issue by victorhhugo128** [benadida/helios-server#358]
I got it installed on my computer, the server is running, everything seems to be working fine but the votes aren't counting. The voters appear on the list of voters but no votes are registered. Does anyone know what is going on?

**Comment by felixdoerre** [comment]
This is very little information on what exactly you did and what errors you encountered, but my first guess would be, that you didn't start the celery worker: https://github.com/benadida/helios-server/blob/master/Procfile#L2 Do you have a rabbit-mq instance running for the communication between the web-worker and celery?

**Comment by victorhhugo128** [comment]
You were right. I didn't start the celery worker. I've done it and now it's working. Thank you so much!!
