### ISSUE TITLE
opening voting before freezing users?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [benadida/helios-server#363]
hi there,

we have some people that would prefer to be able to vote at their leisure a while before we close an election, while others may only join (and become eligible as a voter) not long before the end of an election.

it appears that Helios currently does not support such a use-case, instead expecting administrators to, in sequence:
- add voters
- freeze the voter list
- let people vote

i was wondering if that design was incidental, or if it this limitation is an integral part of Helios's verifiability.
in the [original paper](https://www.usenix.org/legacy/events/sec08/tech/full_papers/adida/adida.pdf), I tried to consult the section 'Freezing the Election' on this topic, but found that unfortunately it seems focused more on describing the process itself than the thought process behind it.

**Comment by shirlei** [comment]
@KiaraGrouwstra don't you mean freeze the ballot? You have to freeze the ballot, not the voter list. Eligible voters depend on your election configuration and they can vote as long as the election is open...

**Comment by KiaraGrouwstra** [comment]
my bad, apologies!
