### ISSUE TITLE
Vote can be submitted multiple times

### ISSUE THREAD

**Issue by iuliach** [benadida/helios-server#384]
1. Open URL received on email: https://vote.heliosvoting.org/helios/e/alegeri-stud-master-i/vote
2. Enter ID and password
3. Click on Start
4. Vote options
5. Submit vote
6. Click on Cast this ballot
7. Open again same URL
8. Enter ID and password
9. Click on Start
10. Vote options 
11. Submit vote

Expected results:
Vote should be submitted only once

Actual results:
Vote can be submitted each time the URL is accessed

Note:
User email is gmail and browser is Google Chrome

**Comment by benadida** [comment]
This is a feature – if anything goes wrong in submitting your vote, you can always submit a new one. Only the last one counts.
