### ISSUE TITLE
Impossible to allow voting to anyone

### ISSUE THREAD

**Issue by remixtj** [benadida/helios-server#50]
If i configure the election to "Anyone can vote" then, once freezed the election on the "Voters & Ballot Tracking Center" i get this:

Who can vote?

any g user
any o user
any o user
any g user
any l user
any e user

This, in fact match what's on the database:
<pre>
helios=# select eligibility from helios_election;
                                                 eligibility                                                              
--------------------------------------------------------------------------------------------------------------------------
 [{"auth_system": "g"}, {"auth_system": "o"}, {"auth_system": "o"}, {"auth_system": "g"}, {"auth_system": "l"}, {"auth_system": "e"}]
(1 row)
</pre>
Why this happens? For what reason the login system "google" is treated as a sequence of chars?

**Comment by benadida** [comment]
with the new approach to get this from the environment and the explicit splitting across commas, this shouldn't happen anymore.
