### ISSUE TITLE
Registering changes on voter list

### ISSUE THREAD

**Issue by remixtj** [benadida/helios-server#55]
When the election has been started is still possible to replace voters. This is a good behaviour, since allows to change an invalid/not working email address. This is, however, also an issue when using anonymous elections: if the administrator of the election is bribed, he can remove some voters and replace with email addresses where he has access and then insert bogus votes, potentially changing the result of the election.

**Comment by benadida** [comment]
after a couple more years of experience here, my conclusion is that the administrator of the election has to at least be trusted with the list of eligible voters, otherwise it's just a mess. So I'm going to close this one, as I don't think this is fixable in a usable way.
