### ISSUE TITLE
Add LICENSE.md file etc (if desire open source license).

### ISSUE THREAD

**Issue by kfogel** [benadida/helios-server#72]
So glad to see this software here!  It looks like it's meant to be open source.  If so, it would be good to add a LICENSE.md file containing the specific open source license, and add license header comments to the source flies (basically as per http://opensource.org/faq#apply-license).

By the way, I'd be happy to contribute the pull request for all this, if you say what license you'd like (http://opensource.org/licenses/ is a good starting place; see also http://choosealicense.com/).

Best,
-Karl

**Comment by benadida** [comment]
@kfogel yes thank you! If you're up for providing a PR, I'd love it. Apache License please.

**Comment by kfogel** [comment]
@benadida, hey -- am actively working on this; PR coming soon, probably next week (delayed by some client work right now).

**Comment by benadida** [comment]
thanks @kfogel ! No worries, I'll take your contribution when you have it.

**Comment by cecilia-donnelly** [comment]
Okay, @benadida, handing over to you to finish this one but let me or @kfogel know if you have any questions.

**Comment by benadida** [comment]
looks good, I have emailed the mailing list to make sure no objections to Apache 2.0, and will merge if no objections.

**Comment by kfogel** [comment]
Sounds good!  Note there's more to be done than just merging this PR -- it adds the LICENSE file, which is the main thing, and then adds a few source file copyright notice headers to show how that's done.  But it'll be easier for you than for us to add those notices to the other source files (and the copyright-diviniation.sh script is meant to partly automate that process).

**Comment by benadida** [comment]
have the license file, I think this will be good enough (I know the best practice is every file, but ... one top-level file seems good enough for most projects.
