### ISSUE TITLE
make it clear that voters needs to be explicitly emailed

### ISSUE THREAD

**Issue by benadida** [benadida/helios-server#74]

**Comment by rhz** [comment]
maybe after freezing the ballot and opening the election, it should say "email voters" instead of "compute encrypted tally" :)
also, after releasing the results it could invite us to send an email notifying the voters of the results.
hope this helps.

**Comment by benadida** [comment]
@rhz great suggestion.

On your second point: it should already be doing this: sending you to the email screen after releasing the tally. Did you notice that, or did something malfunction?

**Comment by rhz** [comment]
Last time I tried it went to the main menu after releasing the tally iirc. I'm making a new test election now (because I'm writing a guide in spanish to run elections on Helios) so I'll let you know what happens.

PS: btw, a bit off-topic here but what are valid identifiers for voters?

**Comment by rhz** [comment]
I just finished the test election and it didn't send me to the email screen after releasing the tally. It sent me instead to the main menu saying "this election is complete". Maybe I'm doing something wrong?
