### ISSUE TITLE
socialbuttons.html should load scripts over https

### ISSUE THREAD

**Issue by davidwagner** [benadida/helios-server#86]
socialbuttons.html contains

    <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share">

and

    <script type="text/javascript" src="http://platform.twitter.com/widgets.js">

Notice that it is loading those scripts from a third-party server, and over http (not https).  By default, socialbuttons.html is served from the same host and same origin as the rest of the Helios server (unless SOCIALBUTTONS_URL_HOST is set in the environment).

Consequences: A man-in-the-middle can modify those scripts and inject malicious Javascript.  In the default settings, that Javascript will run within the same origin of the Helios server, so it can do anything the other Helios code can do, and it can attack the rest of Helios (defeat vote privacy, try to steal vote credentials, etc.).

Those scripts should be loaded over https.  I think it makes sense to hardcode the https version of those URLs.

Suggested change: http://platform.twitter.com/widgets.js -> https://platform.twitter.com/widgets.js, http://static.ak.fbcdn.net/connect.php/js/FB.Share -> https://s-static.ak.fbcdn.net/connect.php/js/FB.Share

**Comment by RunasSudo** [comment]
> https://s-static.ak.fbcdn.net/connect.php/js/FB.Share

This results in an Access Denied error. The API used is deprecated and does not appear to support HTTPS.

**Comment by davidwagner** [comment]
OK.  Thanks for the explanation/clarification, RunasSudo!  Then it sounds like a different fix will be needed... but regardless, if I understand the situation correctly, the vulnerability remains, so it still needs to be fixed.

Perhaps the Facebook share (FB.Share) button needs to be removed, until it can be replaced with a secure alternative that doesn't render Helios vulnerable to MITM attacks.

**Comment by benadida** [comment]
@davidwagner - note that on all production sites that I run, I set the host to be different, and the IFRAME does provide that isolation. It's very difficult to provide that isolation "by default" because you do need a second origin to make that work.

All that said, given low usage of this feature, I've taken it out entirely on the latest master. I don't think it's worth the pain of configuration. Let me know if you need it and we can brainstorm a better way to do it :)
