### ISSUE TITLE
socialbuttons.html should not load external scripts within the Helios origin

### ISSUE THREAD

**Issue by davidwagner** [benadida/helios-server#87]
socialbuttons.html contains

    <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share">

and

    <script type="text/javascript" src="http://platform.twitter.com/widgets.js">

Notice that it is loading those scripts from a third-party server.  By default, socialbuttons.html is served from the same host and same origin as the rest of the Helios server (unless SOCIALBUTTONS_URL_HOST is set in the environment).

If static.ak.fbcdn.net or platform.twitter.com are compromised or malicious, they can serve malicious Javascript that attacks Helios (e.g., compromising voter privacy, trying to steal voter's credentials).  This creates a dependency on a third-party server.  The rest of Helios is designed to avoid these dependencies, e.g., by serving a static copy of jQuery and so on -- this defeats that design goal.

I'm not sure what the best fix is.

One possible alternative would be to embed the like/tweet buttons via an iframe, with the iframe src set to Twitter and Facebook's domain (so it's not hosted in the Helios origin).  However, I don't know whether this would allow you to maintain the same visual look and feel.

Another possible alternative is to use HTML5's sandbox attribute on the iframe to make it run in a temporary origin.  Change

    <iframe src="{{socialbuttons_url}}" ...>

to

    <iframe src="{{socialbuttons_url}}" sandbox="allow-scripts allow-forms allow-popups">

and in particular, without including allow-same-origin in the sandbox specification.  However, I haven't checked whether this would actually work (if you're logged into Facebook/Twitter, will it work seamlessly without requiring you to log in?).

See also http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/

**Comment by benadida** [comment]
so this was set up to be done securely with the separate host, which of course you do have to set up when you're installing Helios, not sure it could have been done differently? Maybe the sandbox attribute.

In any case this feature was so under-utilized that I've removed it :)

**Comment by shirlei** [comment]
@benadida I agree with you.. In my institution we had it removed.
