### ISSUE TITLE
Secure deployment guidelines

### ISSUE THREAD

**Issue by davidwagner** [benadida/helios-server#90]
Users of Helios might benefit from having a document that provides some recommended guidelines for securely deploying Helios, for settings where security is important).  Some possible topics and reminders:
1. Deploy Helios as SSL-only.  (Not the default, but provides hardening/robustness.)  Check the server SSL configuration with Qualys SSL tester.
2. Enable HSTS (Strict Transport Security): defends against man-in-the-middle attacks and SSL stripping attacks.

These currently aren't mentioned in helios-server/INSTALL.md or http://documentation.heliosvoting.org/install

**Comment by benadida** [comment]
I would love a PR on this one :)
