### ISSUE TITLE
Consider avoiding use of document.write()

### ISSUE THREAD

**Issue by davidwagner** [benadida/helios-server#92]
Minor nit:

jscrypto/helios.js open_window_with_content() uses document.write().  To ease code review, you could consider avoiding this pattern.

In particular, it appears that Helios is using string concatenation to build up HTML dynamically and then writing it to the page with document.write().  As a result, code reviewers must check each such instance to ensure it does not introduce DOM-based XSS.

I found two instances of this: download_sk() in election_keygenerator.html, e.g.:

```
UTILS.open_window_with_content(jQuery.toJSON(SECRET_KEY), "application/json");
```

and show_receipt() in heliosbooth/vote.html, e.g.:

```
UTILS.open_window_with_content("Your smart ballot tracker for " + BOOTH.election.name + ": " + BOOTH.encrypted_ballot_hash);
```

A code reviewer has to verify that `BOOTH.election.name` and `BOOTH.encrypted_ballot_hash` are properly sanitized or escaped.  In this case, I believe that they are.

See also http://www.educatedguesswork.org/2011/08/guest_post_adam_barth_on_three.html

**Comment by benadida** [comment]
Yeah, the tricky part is that I want these `window.open` calls to be done with no server calls, since I want the private key to never go over the network. I'd welcome suggestions on how to do that without `document.write`, it may well be possible!
