### ISSUE TITLE
FR: LDAP authentication

### ISSUE THREAD

**Issue by zakkak** [benadida/helios-server#94]
Hello, I would like to request an extension enabling LDAP authentication.

**Comment by shirlei** [comment]
Hi ! I've developed such extension for the institution I work for - www.ifsc.edu.br. It is avaliable at helios.ifsc.edu.br. Currently, I've made a pull request (https://github.com/benadida/helios-server/pull/100) and I'm waiting for him to analyze it.

**Comment by zakkak** [comment]
That's great! Thanks for the information.
