### ISSUE TITLE
Compromised browser & coercion 

### ISSUE THREAD

**Issue by dan-klasson** [benadida/helios-server#98]
To prevent a hijacker to seize control of client computers, why not require extra server based authentication for the vote API and have the back-end server encrypt the ballot instead of the client? In addition, if captcha was added to the cast vote page, it should render it impossible for a hijacker to compromise a browser.

In regards to coercion, would it not be possible to add a user password to the hash? So that if anyone came across the email with the url to the voting booth, it would make it impossible for any coercer to guess what you actually voted for. Would that be a security issue or perhaps require longer computational time?

**Comment by dmgawel** [comment]
That is the whole idea behind Helios: elections are truly private. You don't have to trust server (election hoster) and share your unecrypted ballot with them.

If you want to learn more about Helios protocol: https://www.usenix.org/legacy/events/sec08/tech/full_papers/adida/adida.pdf

**Comment by dan-klasson** [comment]
I don't think you understand what I am referring to. In my first paragraph I'm referring to the client web interface, and in the second, the feature where you can see who you are voting for (if that is enabled). 

If I am not totally mistaken that is, it's been a while since I've looked at the code. Too bad there isn't much interest in this project.

**Comment by dmgawel** [comment]
Correct me please if I got it wrong: To make sure vote is encypted correctly you propose sending it from client to server and encrypting on server-side. Right? In this scenario you have to trust server (election hoster). If someone takes control over server or election hoster is malicious he can store also your unencrypted vote. This leads to breaking privacy of election.

**Comment by benadida** [comment]
@dan-klasson: I don't think having the server encrypt the ballot would really help, since an attacker that has compromised the client could intercept the plaintext ballot request and alter it.

Yes, this project moves somewhat slowly, though that is partly because Helios works pretty well as is :)

Closing this for now, please reopen if I misinterpreted your point.
