### ISSUE TITLE
Editing an election question resets the ballot type

### ISSUE THREAD

**Issue by sigmavirus24** [benadida/helios-server#99]
At present moment an administrator sees:

> Select between [dropdown - default: 0] and [dropdown - default: 1] answers.

If I select "approval", save the question, then go back and edit it, it restores the default to 1 instead of honoring the previous selection.

I would expect that it would preserve the previous value that I had specified instead of resetting it.

**Comment by shirlei** [comment]
Hello! I use the system and I couldn't reproduce this issue... Could you elaborate it a bit more?

**Comment by benadida** [comment]
agree, I can't reproduce, closing
